# Use a base image (e.g., CentOS) as the starting point
FROM ubuntu:22.04

# file author / maintainer
LABEL MAINTAINER="Nabeel Hassan <thenabeelhassan@gmail.com>"

# Install linux/unix utilities (Java 8 or later is recommended)
RUN apt-get update && \
    apt-get install -y sudo nano telnet unzip net-tools openjdk-17-jre ca-certificates curl fontconfig wget && \
    apt-get clean all

# Install Docker

# Add Docker's official GPG key:
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
RUN chmod a+r /etc/apt/keyrings/docker.asc
RUN wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian/jenkins.io-2023.key

# Add the repository to Apt sources:
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update
RUN echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

# Installing Docker
RUN apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-compose -y

# Installing Jenkins
RUN apt-get install jenkins -y

RUN systemctl enable jenkins

RUN systemctl start jenkins

# Expose the ports required by JBoss EAP and RHPAM
EXPOSE 8080

# Keep the container running
CMD ["tail", "-f", "/dev/null"]